// @ts-check

/**
 * Service-worker registration + update-toast wiring.
 *
 * Phase A2 PWA (2026-05-09). vite-plugin-pwa exposes two virtual
 * entries: `virtual:pwa-register` (callback form) and
 * `virtual:pwa-register/react` (hook form, `useRegisterSW`). We use the
 * CALLBACK form because the SW glue then stays out of the React
 * reconciliation path; the update flag is wrapped in our own React
 * state inside this component (BUILD-009 docstring fix).
 *
 * registerType: 'prompt' in vite.config.js (not auto-update): a
 * long-running session can be mid-wizard / mid-export when a deploy
 * lands. Auto-update would swap assets out from under in-flight code
 * paths and produce spectacular crashes. Prompt lets the user finish
 * their work, accept the update, and reload cleanly.
 *
 * An open tab does not see a new worker on its own — browsers only
 * check on navigation (plus a slow background timer). After register
 * we poll + re-check on focus/visibility so a deploy can raise the
 * toast without a manual reload. Activation still waits on Reload.
 *
 * @module lib/swRegister
 */

import { useEffect, useRef, useState } from 'react';
import { startPeriodicSwUpdateChecks } from './swUpdateCheck.js';

/**
 * Mount-and-go component. Place once near the AppShell root.
 * Renders nothing when no update is pending; renders a fixed-position
 * toast in the lower-right when an update is ready.
 */
export function ServiceWorkerUpdater() {
  const [needsUpdate, setNeedsUpdate] = useState(false);
  const updateSWRef = useRef(/** @type {((reload?: boolean) => Promise<void>) | null} */ (null));
  const [registered, setRegistered] = useState(false);
  const [error, setError] = useState(/** @type {string | null} */ (null));

  useEffect(() => {
    // Hydrate the registrar lazily so the SW import doesn't enter the
    // boot bundle. The virtual module is generated by vite-plugin-pwa.
    let cancelled = false;
    let refreshNeeded = false;
    let stopChecks = () => {};
    (async () => {
      try {
        // @ts-expect-error virtual module
        const mod = await import('virtual:pwa-register');
        if (cancelled) return;
        const update = mod.registerSW({
          onNeedRefresh() {
            refreshNeeded = true;
            stopChecks();
            if (!cancelled) setNeedsUpdate(true);
          },
          onOfflineReady() {
            if (!cancelled) setRegistered(true);
          },
          onRegisterError(err) {
            if (!cancelled) setError(err && err.message ? err.message : String(err));
          },
          onRegisteredSW(swUrl, registration) {
            if (cancelled || refreshNeeded || !registration) return;
            stopChecks = startPeriodicSwUpdateChecks(swUrl, registration, {
              isCancelled: () => cancelled || refreshNeeded,
            });
          },
        });
        if (!cancelled) updateSWRef.current = update;
      } catch (err) {
        // Dev mode (no SW emitted) or environment without service workers.
        if (!cancelled) setError(err && err.message ? err.message : String(err));
      }
    })();
    return () => {
      cancelled = true;
      stopChecks();
    };
  }, []);

  if (!needsUpdate) {
    // Visibly silent — registered/error states stay internal until the
    // app surfaces them via DevTools / future status-bar UI.
    if (error && typeof console !== 'undefined') {
      console.warn('[swRegister] register error:', error);
    }
    if (registered && typeof console !== 'undefined') {
      console.info('[swRegister] offline-ready');
    }
    return null;
  }

  return (
    <div
      role="status"
      aria-live="polite"
      style={{
        position: 'fixed',
        right: 16,
        bottom: 16,
        zIndex: 9999,
        background: 'hsl(var(--background))',
        color: 'hsl(var(--foreground))',
        border: '1px solid hsl(var(--border))',
        borderRadius: 6,
        padding: '12px 16px',
        boxShadow: '0 4px 12px rgba(0,0,0,0.25)',
        fontSize: 13,
        display: 'flex',
        flexDirection: 'column',
        gap: 8,
        maxWidth: 280,
      }}
    >
      <div style={{ fontWeight: 600 }}>Update available</div>
      <div style={{ fontSize: 12, color: 'hsl(var(--muted-foreground))' }}>
        A newer version of Stretchy Studio is ready. Reload to get it?
      </div>
      <div style={{ display: 'flex', gap: 8, justifyContent: 'flex-end' }}>
        <button
          type="button"
          onClick={() => setNeedsUpdate(false)}
          style={{
            background: 'transparent',
            border: '1px solid hsl(var(--border))',
            color: 'hsl(var(--foreground))',
            borderRadius: 4,
            padding: '4px 10px',
            cursor: 'pointer',
            fontSize: 12,
          }}
        >
          Later
        </button>
        <button
          type="button"
          onClick={() => { void updateSWRef.current?.(true); }}
          style={{
            background: 'hsl(var(--foreground))',
            color: 'hsl(var(--background))',
            border: 'none',
            borderRadius: 4,
            padding: '4px 10px',
            cursor: 'pointer',
            fontSize: 12,
            fontWeight: 600,
          }}
        >
          Reload
        </button>
      </div>
    </div>
  );
}
