// @ts-check

/**
 * Per-part rig warp deformer emit (Section 3c) for the .cmo3 generator.
 *
 * Lifted out of cmo3writer.js (Phase 6 god-class breakup, sweep #43).
 *
 * For every mesh whose tag matches a `RIG_WARP_TAGS` entry (the curated
 * set of deformable body parts: hair, skirt, shirt, pants, brows, mouth,
 * eyes…), emits a CWarpDeformerSource whose grid covers the mesh's
 * canvas-space bounding box (with 10 % padding). Tag bindings drive
 * keyform generation:
 *
 *   - **User-authored** (`rigWarps[partId]._userAuthored`, e.g. a spring
 *     chain) — bindings + keyforms come from the stored warp, not the
 *     tag table. Without this, Cubism export rebinds the warp to
 *     ParamHairFront / ParamSkirt / … while Bake Physics and physics3
 *     write `ParamSpring_*`, so the Viewer shows a dead spring.
 *
 *   - **Bound** (entry in `TAG_PARAM_BINDINGS`) — N keyforms via cartesian
 *     product over the binding's keys, each keyform generated by the
 *     binding's procedural `shiftFn` (rest grid + delta in 0..1 space).
 *     Eye parts pass an extra `meshCtx` with the shared eye-closure
 *     `curvePoints` so all three eye parts collapse to the same line.
 *
 *   - **Stored** (entry in `rigWarps`, Stage 9b / spring) — keyform
 *     *deltas* come from the stored `keyforms[ki].positions`, rebased
 *     onto the export rest grid (parent 0..1). Bypasses the procedural
 *     shiftFn; same XML shape.
 *
 *   - **Unbound** — single rest keyform on a no-op `ParamOpacity[1.0]`
 *     binding. Lets the warp exist as a rigid pass-through container
 *     (still gets re-parented under the body chain in section 3d).
 *
 * Grid coordinates rebase per parent space:
 *   - Face-parallax tags → canvas → FaceParallax 0..1 (`canvasToFaceUnion*`)
 *   - Neck-warp tags     → canvas → NeckWarp 0..1     (`canvasToNeckWarp*`)
 *   - Default            → canvas → Body X 0..1       (`canvasToBodyXX/Y`)
 *
 * Outputs (all mutated in place):
 *   - `meshWarpDeformerGuids` — partId → pidRigWarpGuid (Section 4 lookup).
 *   - `rigWarpBbox` — partId → canvas-space bbox (Section 4 0..1 conversion).
 *   - `rigWarpDebugInfo` — partId → grid corner positions (eye parts only).
 *   - `rigWarpTargetNodesToReparent` — push entries the structural chain
 *     emit consumes when re-parenting all per-part warps to their final
 *     body-warp parent.
 *   - `rigCollector.warpDeformers` — append a `WarpDeformerSpec` per
 *     emitted rig warp (moc3 binary writer's source of truth).
 *   - `allDeformerSources` — append the new pid + tag.
 *
 * @module io/live2d/cmo3/perPartRigWarps
 */

import { uuid } from '../xmlbuilder.js';
import { sanitisePartName } from '../../../lib/partId.js';
import { emitKfBinding } from './deformerEmit.js';
import { RIG_WARP_TAGS, FACE_PARALLAX_TAGS, NECK_WARP_TAGS } from './rigWarpTags.js';
import { EYE_PART_TAGS } from './eyeTags.js';
import { logger } from '../../../lib/logger.js';
import { resolveWarpGridDims } from '../rig/springChain.js';
import { isRigidFollowExtra } from '../rig/rigidFollowExtra.js';

/**
 * Prefer a user-authored warp's bindings (spring chains) over the tag
 * default. Returns the same `{ bindings: [{pid, keys, desc}], shiftFn }`
 * shape `tagParamBindings` uses, or null to fall through.
 *
 * @param {object|null|undefined} stored
 * @param {Array<{id?: string, pid?: string}>|null|undefined} paramDefs
 * @returns {{ bindings: Array<{pid: string, keys: number[], desc: string}>, shiftFn: null } | null}
 */
export function resolveAuthoredWarpBindings(stored, paramDefs) {
  if (!stored || stored._userAuthored !== true) return null;
  const authored = stored.bindings;
  if (!Array.isArray(authored) || authored.length === 0) return null;
  const pidById = new Map();
  for (const p of paramDefs ?? []) {
    if (p?.id && p.pid) pidById.set(p.id, p.pid);
  }
  /** @type {Array<{pid: string, keys: number[], desc: string}>} */
  const bindings = [];
  for (const b of authored) {
    if (!b?.parameterId || !Array.isArray(b.keys) || b.keys.length === 0) return null;
    const pid = pidById.get(b.parameterId);
    if (!pid) {
      logger.warn('perPartRigWarps', `authored binding "${b.parameterId}" has no CParameterGuid — keeping tag bindings`);
      return null;
    }
    bindings.push({ pid, keys: b.keys.slice(), desc: b.parameterId });
  }
  return { bindings, shiftFn: null };
}

/**
 * Transfer a stored keyform onto the export rest grid by copying
 * per-point deltas, scaled by each axis's rest span.
 *
 * Stored spring keyforms live in the warp's authoring frame (often
 * canvas-px, sometimes an older 0..1 rest). Export `restGrid` is
 * always parent 0..1. A verbatim copy either explodes the mesh or
 * crushes the swing; this keeps the authored motion as a fraction
 * of the parent warp.
 *
 * @param {ArrayLike<number>|null|undefined} storedKf
 * @param {ArrayLike<number>|null|undefined} storedRest
 * @param {ArrayLike<number>} exportRest
 * @returns {Float64Array}
 */
export function rebaseKeyformOntoRest(storedKf, storedRest, exportRest) {
  const n = exportRest.length;
  const out = new Float64Array(exportRest);
  if (!storedKf || !storedRest || storedKf.length < n || storedRest.length < n) {
    return out;
  }
  let sMinX = Infinity;
  let sMaxX = -Infinity;
  let sMinY = Infinity;
  let sMaxY = -Infinity;
  let eMinX = Infinity;
  let eMaxX = -Infinity;
  let eMinY = Infinity;
  let eMaxY = -Infinity;
  for (let i = 0; i < n; i += 2) {
    const sx = storedRest[i];
    const sy = storedRest[i + 1];
    const ex = exportRest[i];
    const ey = exportRest[i + 1];
    if (sx < sMinX) sMinX = sx;
    if (sx > sMaxX) sMaxX = sx;
    if (sy < sMinY) sMinY = sy;
    if (sy > sMaxY) sMaxY = sy;
    if (ex < eMinX) eMinX = ex;
    if (ex > eMaxX) eMaxX = ex;
    if (ey < eMinY) eMinY = ey;
    if (ey > eMaxY) eMaxY = ey;
  }
  const sSpanX = sMaxX - sMinX;
  const sSpanY = sMaxY - sMinY;
  const eSpanX = eMaxX - eMinX;
  const eSpanY = eMaxY - eMinY;
  const scaleX = sSpanX > 1e-9 ? eSpanX / sSpanX : 1;
  const scaleY = sSpanY > 1e-9 ? eSpanY / sSpanY : 1;
  for (let i = 0; i < n; i += 2) {
    out[i] = exportRest[i] + (storedKf[i] - storedRest[i]) * scaleX;
    out[i + 1] = exportRest[i + 1] + (storedKf[i + 1] - storedRest[i + 1]) * scaleY;
  }
  return out;
}

function storedRestGrid(storedRigWarp, exportRest) {
  const base = storedRigWarp?.baseGrid;
  if (base && base.length === exportRest.length) return base;
  const restKf = storedRigWarp?.keyforms?.find((k) =>
    Array.isArray(k?.keyTuple) && k.keyTuple.length > 0 && k.keyTuple.every((v) => v === 0));
  if (restKf?.positions && restKf.positions.length === exportRest.length) {
    return restKf.positions;
  }
  return exportRest;
}

/**
 * Emit one CWarpDeformerSource per mesh whose tag matches RIG_WARP_TAGS,
 * mutating every accumulator listed in the module-level docstring.
 *
 * @param {import('./emitContext.js').EmitContext} ctx
 * @param {Object} opts
 * @param {(cx: number) => number} opts.canvasToBodyXX
 * @param {(cy: number) => number} opts.canvasToBodyXY
 * @param {any} opts.faceUnionBbox
 * @param {(cx: number) => number} opts.canvasToFaceUnionX
 * @param {(cy: number) => number} opts.canvasToFaceUnionY
 * @param {any} opts.neckUnionBbox
 * @param {(cx: number) => number} opts.canvasToNeckWarpX
 * @param {(cy: number) => number} opts.canvasToNeckWarpY
 * @param {Map<string, any>} opts.eyeUnionBboxPerSide
 * @param {Map<string, any>} opts.tagParamBindings
 * @param {Map<string, string>} opts.meshWarpDeformerGuids
 * @param {Map<string, {gridMinX: number, gridMinY: number, gridW: number, gridH: number}>} opts.rigWarpBbox
 * @param {Map<string, any>} opts.rigWarpDebugInfo
 * @param {Array<any>} opts.rigWarpTargetNodesToReparent
 * @param {(tag: string, bboxCx: number, bboxCy: number) => any} opts.findEyeCtx
 * @param {Map<string, any>} opts.groupParts
 * @param {any} opts.rootPart
 * @param {Array<{pid: string, tag: string}>} opts.allDeformerSources
 */
export function emitPerPartRigWarps(ctx, opts) {
  const {
    x, meshes, perMesh, generateRig,
    pidPartGuid, pidDeformerRoot, pidCoord, pidParamOpacity,
    groupPartGuids,
    rigCollector, rigDebugLog,
    rigWarps, paramDefs, project,
  } = ctx;
  const {
    canvasToBodyXX, canvasToBodyXY,
    faceUnionBbox, canvasToFaceUnionX, canvasToFaceUnionY,
    neckUnionBbox, canvasToNeckWarpX, canvasToNeckWarpY,
    eyeUnionBboxPerSide,
    tagParamBindings,
    meshWarpDeformerGuids,
    rigWarpBbox,
    rigWarpDebugInfo,
    rigWarpTargetNodesToReparent,
    findEyeCtx,
    groupParts,
    rootPart,
    allDeformerSources,
  } = opts;

  if (!generateRig) {
    logger.debug('perPartRigWarps', 'generateRig=false — skipping all per-part warps');
    return;
  }

  // BUG-018 instrumentation — surface every reason a mesh is skipped, plus
  // every emit, so the user can confirm exactly which path the front-hair
  // mesh takes when its RigWarp goes missing post-Init-Rig. Filtered logging
  // would have to know the tag spelling (`'front hair'` vs `'front_hair'`
  // vs something else); unfiltered is noisy but unambiguous.
  let skipped_noTag = 0, skipped_alreadyEmitted = 0, skipped_rigidFollow = 0, emitted = 0;
  const partsById = new Map();
  for (const n of project?.nodes ?? []) {
    if (n?.type === 'part' && typeof n.id === 'string') partsById.set(n.id, n);
  }

  for (const pm of perMesh) {
    const m = meshes[pm.mi];
    if (m.partId && isRigidFollowExtra(partsById.get(m.partId))) {
      skipped_rigidFollow += 1;
      logger.debug('perPartRigWarps.skip', `rigid-follow extra — no BodyX RigWarp`, {
        partId: m.partId, meshName: pm.meshName, tag: m.tag,
      });
      continue;
    }
    const warpSpec = RIG_WARP_TAGS.get(m.tag);
    if (!warpSpec) {
      skipped_noTag += 1;
      logger.debug('perPartRigWarps.skip', `tag '${m.tag}' not in RIG_WARP_TAGS`, {
        partId: m.partId, meshName: pm.meshName, tag: m.tag,
        variantOf: m.variantOf ?? null, variantSuffix: m.variantSuffix ?? null,
      });
      continue;
    }
    if (meshWarpDeformerGuids.has(m.partId)) {
      skipped_alreadyEmitted += 1;
      logger.debug('perPartRigWarps.skip', `partId already has rigWarp guid`, {
        partId: m.partId, meshName: pm.meshName, tag: m.tag,
      });
      continue;
    }
    // Bug-03 closure (2026-06-02, rigInvariantCheck I-20 trace named the
    // source): bone-baked parts (handwear) previously skipped rigwarp
    // emission because per-param keyform variation isn't needed (bone
    // overlay handles deformation). The skip was over-aggressive: the
    // rigwarp ALSO serves as a per-part FRAME NORMALIZER — it gives the
    // part's keyforms a UV [0,1] storage frame (artMeshSourceEmit.js:177
    // `if (rwBox)` branch) and provides a leaf-cage matching the part's
    // spatial extent. Without it, bone-baked keyforms are stored in
    // canvas-px and fed to a body-warp leaf (e.g. BodyXWarp) whose
    // cubismWarpEval expects UV [0,1] input — corner-zone extrapolation
    // produced 800x bbox blowup (handwear-l/r 173k×1.26M on 1792
    // canvas). Emit the rigwarp anyway; the `else` branch at line ~332
    // produces a single-rest keyform on ParamOpacity[1.0] when no
    // body-angle binding exists for the tag (handwear has none), so the
    // emitted rigwarp is an identity frame-normalizer. Bone overlay
    // still applies post-chain via the always-appended Armature
    // modifier — bone-driven deformation unchanged.
    emitted += 1;
    logger.debug('perPartRigWarps.emit', `RigWarp_${m.partId}`, {
      partId: m.partId, meshName: pm.meshName, tag: m.tag,
      gridCol: warpSpec.col, gridRow: warpSpec.row,
    });

    const storedRigWarp = rigWarps?.get?.(m.partId) ?? null;
    const authoredBinding = resolveAuthoredWarpBindings(storedRigWarp, paramDefs);
    let { col: warpCol, row: warpRow } = warpSpec;
    if (authoredBinding) {
      const restForDims = storedRigWarp.baseGrid
        ?? storedRigWarp.keyforms?.[0]?.positions
        ?? null;
      const dims = restForDims ? resolveWarpGridDims(storedRigWarp, restForDims) : null;
      if (dims && dims.gW >= 2 && dims.gH >= 2) {
        warpCol = dims.gW - 1;
        warpRow = dims.gH - 1;
      }
    }
    const warpGridPts = (warpCol + 1) * (warpRow + 1);

    const partId = m.partId;
    const canvasVerts = pm.vertices;
    const numVerts = canvasVerts.length / 2;
    const sanitizedName = sanitisePartName(pm.meshName || partId);

    // Bounding box in canvas space — use FULL extent so every mesh vertex stays
    // inside the warp grid (0..1 space). Percentile-filtered bbox caused outlier
    // vertices to have <0 or >1 warp-local coords, producing bad extrapolation
    // (vertices "sticking out" at closed keyforms).
    let bxMin = Infinity, byMin = Infinity, bxMax = -Infinity, byMax = -Infinity;
    for (let i = 0; i < numVerts; i++) {
      const vx = canvasVerts[i * 2], vy = canvasVerts[i * 2 + 1];
      if (vx < bxMin) bxMin = vx; if (vy < byMin) byMin = vy;
      if (vx > bxMax) bxMax = vx; if (vy > byMax) byMax = vy;
    }
    // P11: extend eye-part rig warp bbox to eye union bounds. Needed because
    // the closure band may fall outside the mesh's own bbox (e.g., waifu L eye:
    // eyewhite extends 19 px below eyelash → band is outside lash bbox →
    // P5 clamp squashes lash to its own max, leaving gap with eyewhite/iris
    // closed lines). Union bbox ensures all eye-part meshes share a common
    // warp domain that covers the band.
    if (EYE_PART_TAGS.has(m.tag)) {
      const side = m.tag.endsWith('-l') ? 'l' : m.tag.endsWith('-r') ? 'r' : null;
      const unionBb = side ? eyeUnionBboxPerSide.get(side) : null;
      if (unionBb) {
        if (unionBb.minX < bxMin) bxMin = unionBb.minX;
        if (unionBb.minY < byMin) byMin = unionBb.minY;
        if (unionBb.maxX > bxMax) bxMax = unionBb.maxX;
        if (unionBb.maxY > byMax) byMax = unionBb.maxY;
      }
    }
    const padX = (bxMax - bxMin) * 0.1 || 10;
    const padY = (byMax - byMin) * 0.1 || 10;
    bxMin -= padX; byMin -= padY; bxMax += padX; byMax += padY;
    const bW = bxMax - bxMin;
    const bH = byMax - byMin;

    // rigWarpBbox stays in canvas space (used for mesh 0..1 conversion in section 4)
    rigWarpBbox.set(partId, { gridMinX: bxMin, gridMinY: byMin, gridW: bW, gridH: bH });

    // Grid positions: in parent warp's 0..1 local space.
    // Face-parallax tags → grid in single FaceParallax 0..1 (rebased via faceUnionBbox).
    // Neck-warp tags    → grid in single NeckWarp 0..1 (rebased via neckUnionBbox).
    // Everything else   → grid in Body X 0..1 (via canvasToBodyXX/Y).
    const isFaceTag = FACE_PARALLAX_TAGS.has(m.tag) && faceUnionBbox;
    const isNeckTag = !isFaceTag && NECK_WARP_TAGS.has(m.tag) && neckUnionBbox;
    const gW = warpCol + 1;
    const gH = warpRow + 1;
    const restGrid = new Float64Array(warpGridPts * 2);
    for (let r = 0; r < gH; r++) {
      for (let c = 0; c < gW; c++) {
        const idx = (r * gW + c) * 2;
        const cx = bxMin + c * bW / warpCol;
        const cy = byMin + r * bH / warpRow;
        if (isFaceTag) {
          restGrid[idx]     = canvasToFaceUnionX(cx);
          restGrid[idx + 1] = canvasToFaceUnionY(cy);
        } else if (isNeckTag) {
          restGrid[idx]     = canvasToNeckWarpX(cx);
          restGrid[idx + 1] = canvasToNeckWarpY(cy);
        } else {
          restGrid[idx]     = canvasToBodyXX(cx);
          restGrid[idx + 1] = canvasToBodyXY(cy);
        }
      }
    }

    // Path C diagnostic: capture rig-warp grid corners for eye parts.
    // Lets us verify the grid is positioned correctly in its parent's coord space
    // (FaceParallax 0..1 for eye parts). If grid corners are off, rendering
    // displacement has nothing to do with the closure algorithm.
    if (rigDebugLog && EYE_PART_TAGS.has(m.tag)) {
      const cornerIdx = (r, c) => (r * gW + c) * 2;
      const tl = cornerIdx(0, 0);
      const tr = cornerIdx(0, gW - 1);
      const bl = cornerIdx(gH - 1, 0);
      const br = cornerIdx(gH - 1, gW - 1);
      rigWarpDebugInfo.set(partId, {
        parentSpace: isFaceTag ? 'FaceParallax 0..1'
                   : isNeckTag ? 'NeckWarp 0..1'
                   : 'Body X 0..1',
        gridDim: { cols: gW, rows: gH },
        gridCanvasBbox: { minX: bxMin, minY: byMin, W: bW, H: bH },
        gridCorners_parentSpace: {
          topLeft:     [restGrid[tl],     restGrid[tl + 1]],
          topRight:    [restGrid[tr],     restGrid[tr + 1]],
          bottomLeft:  [restGrid[bl],     restGrid[bl + 1]],
          bottomRight: [restGrid[br],     restGrid[br + 1]],
        },
      });
    }

    const [, pidRigWarpGuid] = x.shared('CDeformerGuid', { uuid: uuid(), note: `RigWarp_${sanitizedName}` });
    meshWarpDeformerGuids.set(partId, pidRigWarpGuid);

    // ── Mesh orientation context (Session 16: unified eye closure) ──
    // For eye parts (eyelash/eyewhite/irides): use shared eyeContext (computed
    // from eyelash) so all three compress to the SAME convergence line.
    // For other face tags: no ctx (shiftFn uses local grid behavior).
    let meshCtx = null;
    if (EYE_PART_TAGS.has(m.tag)) {
      // Compute this mesh's bbox center in Body X space for proximity matching
      const bCx = canvasToBodyXX((bxMin + bxMax) / 2);
      const bCy = canvasToBodyXY((byMin + byMax) / 2);
      const eyeCtx = findEyeCtx(m.tag, bCx, bCy);
      if (eyeCtx) meshCtx = { curvePoints: eyeCtx.curvePoints };
    }
    // ── Per-part warp binding: authored (spring) > tag param > ParamOpacity ──
    const tagBinding = tagParamBindings.get(m.tag);
    const tagBindingOk = !!(tagBinding && tagBinding.bindings.every((b) => b.pid));
    const activeBinding = authoredBinding ?? (tagBindingOk ? tagBinding : null);
    const hasBinding = !!activeBinding;
    if (authoredBinding) {
      logger.info('perPartRigWarps', `using authored bindings on ${partId}`, {
        partId,
        params: authoredBinding.bindings.map((b) => b.desc),
      });
    }
    let pidRigWarpKfg, rigWarpFormGuids, rigWarpKeyValues;

    if (hasBinding) {
      const { bindings } = activeBinding;
      const numBindings = bindings.length;
      // Generate all key index/value combinations across N bindings via
      // a cartesian product. Emission order matches Cubism's column-
      // major expectation (binding[0] = fastest axis).
      //   bindings[0] = [-1, 0, 1], bindings[1] = [-1, 0, 1], bindings[2] = [-1, 0, 1]
      //   → (0,0,0), (1,0,0), (2,0,0), (0,1,0), (1,1,0), …
      const keyCombos = [];       // [[idx0, idx1, …], …] for KeyOnParameter keyIndex
      rigWarpKeyValues = [];      // [[val0, val1, …], …] for shiftFn
      const idxBuf = new Array(numBindings);
      const valBuf = new Array(numBindings);
      const cartesian = (dim) => {
        if (dim === numBindings) {
          keyCombos.push(idxBuf.slice());
          rigWarpKeyValues.push(valBuf.slice());
          return;
        }
        // Recurse from inner (dim=0) to outer (dim=numBindings-1) — so
        // outer bindings vary slowest in the emitted sequence. Match the
        // original hardcoded 2D order: `for j of b[1]` outside `for i of b[0]`.
        const inv = numBindings - 1 - dim;
        const b = bindings[inv];
        for (let i = 0; i < b.keys.length; i++) {
          idxBuf[inv] = i;
          valBuf[inv] = b.keys[i];
          cartesian(dim + 1);
        }
      };
      cartesian(0);
      const totalKf = keyCombos.length;
      rigWarpFormGuids = [];

      // KeyformBindingSources — one per param
      const kfbs = bindings.map(b => {
        const [kfb, pidKfb] = x.shared('KeyformBindingSource');
        return { kfb, pidKfb, ...b };
      });

      // KeyformGridSource with totalKf keyforms
      const [kfg, pidKfg] = x.shared('KeyformGridSource');
      pidRigWarpKfg = pidKfg;
      const kfogList = x.sub(kfg, 'array_list', {
        'xs.n': 'keyformsOnGrid', count: String(totalKf),
      });
      for (let ki = 0; ki < totalKf; ki++) {
        const [, pidForm] = x.shared('CFormGuid', {
          uuid: uuid(), note: `RigWarpForm_${sanitizedName}_${keyCombos[ki].join('_')}`,
        });
        rigWarpFormGuids.push(pidForm);
        const kog = x.sub(kfogList, 'KeyformOnGrid');
        const ak = x.sub(kog, 'KeyformGridAccessKey', { 'xs.n': 'accessKey' });
        const kop = x.sub(ak, 'array_list', {
          'xs.n': '_keyOnParameterList', count: String(numBindings),
        });
        for (let bi = 0; bi < numBindings; bi++) {
          const kon = x.sub(kop, 'KeyOnParameter');
          x.subRef(kon, 'KeyformBindingSource', kfbs[bi].pidKfb, { 'xs.n': 'binding' });
          x.sub(kon, 'i', { 'xs.n': 'keyIndex' }).text = String(keyCombos[ki][bi]);
        }
        x.subRef(kog, 'CFormGuid', pidForm, { 'xs.n': 'keyformGuid' });
      }
      // Binding list + emit each binding
      const kfbList = x.sub(kfg, 'array_list', {
        'xs.n': 'keyformBindings', count: String(numBindings),
      });
      for (const kfb of kfbs) {
        x.subRef(kfbList, 'KeyformBindingSource', kfb.pidKfb);
        emitKfBinding(x, kfb.kfb, pidKfg, kfb.pid, kfb.keys.map(k => k + '.0'), kfb.desc);
      }
    } else {
      // No standard binding — single rest keyform, no-op ParamOpacity
      const [, pidRigWarpForm] = x.shared('CFormGuid', { uuid: uuid(), note: `RigWarpForm_${sanitizedName}` });
      rigWarpFormGuids = [pidRigWarpForm];
      rigWarpKeyValues = null;
      const [rigWarpKfb, pidRigWarpKfb] = x.shared('KeyformBindingSource');
      const [rigWarpKfg, pidKfg] = x.shared('KeyformGridSource');
      pidRigWarpKfg = pidKfg;
      const kfogList = x.sub(rigWarpKfg, 'array_list', { 'xs.n': 'keyformsOnGrid', count: '1' });
      const kog = x.sub(kfogList, 'KeyformOnGrid');
      const ak = x.sub(kog, 'KeyformGridAccessKey', { 'xs.n': 'accessKey' });
      const kop = x.sub(ak, 'array_list', { 'xs.n': '_keyOnParameterList', count: '1' });
      const kon = x.sub(kop, 'KeyOnParameter');
      x.subRef(kon, 'KeyformBindingSource', pidRigWarpKfb, { 'xs.n': 'binding' });
      x.sub(kon, 'i', { 'xs.n': 'keyIndex' }).text = '0';
      x.subRef(kog, 'CFormGuid', pidRigWarpForm, { 'xs.n': 'keyformGuid' });
      const kfbList = x.sub(rigWarpKfg, 'array_list', { 'xs.n': 'keyformBindings', count: '1' });
      x.subRef(kfbList, 'KeyformBindingSource', pidRigWarpKfb);
      emitKfBinding(x, rigWarpKfb, pidRigWarpKfg, pidParamOpacity, ['1.0'], 'ParamOpacity');
    }

    // Parent part
    const meshParentGroup = m.parentGroupId;
    const rigWarpPartGuid = meshParentGroup && groupPartGuids.has(meshParentGroup)
      ? groupPartGuids.get(meshParentGroup) : pidPartGuid;

    // All per-part warps target ROOT, re-parented to Breath in section 3d.

    // CWarpDeformerSource — grid in Breath 0..1 space
    const [rigWarpDf, pidRigWarpDf] = x.shared('CWarpDeformerSource');
    allDeformerSources.push({ pid: pidRigWarpDf, tag: 'CWarpDeformerSource' });

    const rwAcdfs = x.sub(rigWarpDf, 'ACDeformerSource', { 'xs.n': 'super' });
    const rwAcpcs = x.sub(rwAcdfs, 'ACParameterControllableSource', { 'xs.n': 'super' });
    x.sub(rwAcpcs, 's', { 'xs.n': 'localName' }).text = `${pm.meshName} Warp`;
    x.sub(rwAcpcs, 'b', { 'xs.n': 'isVisible' }).text = 'true';
    x.sub(rwAcpcs, 'b', { 'xs.n': 'isLocked' }).text = 'false';
    x.subRef(rwAcpcs, 'CPartGuid', rigWarpPartGuid, { 'xs.n': 'parentGuid' });
    x.subRef(rwAcpcs, 'KeyformGridSource', pidRigWarpKfg, { 'xs.n': 'keyformGridSource' });
    const rwMft = x.sub(rwAcpcs, 'KeyFormMorphTargetSet', { 'xs.n': 'keyformMorphTargetSet' });
    x.sub(rwMft, 'carray_list', { 'xs.n': '_morphTargets', count: '0' });
    const rwBwc = x.sub(rwMft, 'MorphTargetBlendWeightConstraintSet', { 'xs.n': 'blendWeightConstraintSet' });
    x.sub(rwBwc, 'carray_list', { 'xs.n': '_constraints', count: '0' });
    x.sub(rwAcpcs, 'carray_list', { 'xs.n': '_extensions', count: '0' });
    x.sub(rwAcpcs, 'null', { 'xs.n': 'internalColor_direct_argb' });
    x.sub(rwAcpcs, 'null', { 'xs.n': 'internalColor_indirect_argb' });
    x.subRef(rwAcdfs, 'CDeformerGuid', pidRigWarpGuid, { 'xs.n': 'guid' });
    x.sub(rwAcdfs, 'CDeformerId', { 'xs.n': 'id', idstr: `RigWarp_${sanitizedName}` });
    // targetDeformerGuid: ROOT, patched to Breath in section 3d
    const rigWarpTargetNode = x.subRef(rwAcdfs, 'CDeformerGuid', pidDeformerRoot, { 'xs.n': 'targetDeformerGuid' });

    x.sub(rigWarpDf, 'i', { 'xs.n': 'col' }).text = String(warpCol);
    x.sub(rigWarpDf, 'i', { 'xs.n': 'row' }).text = String(warpRow);
    x.sub(rigWarpDf, 'b', { 'xs.n': 'isQuadTransform' }).text = 'false';

    // ── Keyforms: N procedurally-shifted grids, or 1 rest keyform ──
    const numKf = rigWarpFormGuids.length;
    const rigKfsList = x.sub(rigWarpDf, 'carray_list', { 'xs.n': 'keyforms', count: String(numKf) });
    const gxSpan = restGrid[warpCol * 2] - restGrid[0];
    const gySpan = restGrid[(warpRow * gW) * 2 + 1] - restGrid[1];

    // Per-mesh rig warp spec for moc3 binary translator. Captures the
    // SAME data the XML emission below produces, just in normalised form.
    // Parent will be resolved at re-parenting time (face → FaceParallax,
    // neck → NeckWarp, default → BodyXWarp).
    /** @type {import('../rig/rigSpec.js').WarpDeformerSpec & {targetPartId: string, canvasBbox: {minX:number,minY:number,W:number,H:number}}} */
    const rigWarpSpec = {
      id: `RigWarp_${sanitizedName}`,
      name: `${pm.meshName} Warp`,
      parent: { type: 'warp', id: 'BodyXWarp' }, // re-parenting may override
      // moc3 translator uses this to set the mesh's parent_deformer_index
      // to the rig warp instead of the deepest body warp. partId is the
      // SS project node id; cmo3 path uses the same as the canonical
      // mesh identity.
      targetPartId: m.partId,
      // Canvas-pixel bounding box of this rig warp's grid. moc3 uses
      // this to convert mesh vertex canvas positions to 0..1 of the
      // grid's canvas extent (the convention cmo3 art-mesh emission
      // uses for rig-warp-parented meshes — see lines ~3497-3503).
      canvasBbox: { minX: bxMin, minY: byMin, W: bW, H: bH },
      gridSize: { rows: warpRow, cols: warpCol },
      baseGrid: new Float64Array(restGrid),
      localFrame: 'normalized-0to1',
      bindings: hasBinding
        ? activeBinding.bindings.map(b => ({
            // tagParamBindings / authored bindings store the param id as `desc`;
            // `pid` is the XML reference (only useful inside cmo3 emission).
            parameterId: b.desc ?? 'ParamOpacity',
            keys: b.keys.slice(),
            interpolation: 'LINEAR',
          }))
        : [{ parameterId: 'ParamOpacity', keys: [1], interpolation: 'LINEAR' }],
      keyforms: [],
      isVisible: true,
      isLocked: false,
      isQuadTransform: false,
    };

    // Stage 9b: resolve stored per-mesh keyforms. If a record exists for
    // this partId AND its keyform count + per-keyform position length
    // match the cartesian-product expected shape, the stored positions
    // replace the procedural shiftFn invocation below. On any shape
    // mismatch (e.g. a save where the mesh was re-meshed since seed)
    // we fall back to the inline path — same behaviour as no record.
    const _useStoredRigWarp = !!(storedRigWarp
      && Array.isArray(storedRigWarp.keyforms)
      && storedRigWarp.keyforms.length === numKf
      && storedRigWarp.keyforms.every(k =>
        k && k.positions && k.positions.length === warpGridPts * 2));
    if (authoredBinding && !_useStoredRigWarp) {
      logger.warn('perPartRigWarps', `authored warp on ${partId} has keyform shape mismatch — emitting rest grids`, {
        partId,
        storedCount: storedRigWarp?.keyforms?.length ?? 0,
        expectedCount: numKf,
        expectedPts: warpGridPts * 2,
      });
    }
    const storedRestForRebase = _useStoredRigWarp
      ? storedRestGrid(storedRigWarp, restGrid)
      : restGrid;

    for (let ki = 0; ki < numKf; ki++) {
      // Generate grid positions: stored (Stage 9b / spring) > shiftFn for
      // bound params > rest grid for no-op. Stored case still emits via
      // the same XML path below — Stage 9b is reader-only, the writer
      // shape is unchanged.
      const pos = _useStoredRigWarp
        ? rebaseKeyformOntoRest(
          storedRigWarp.keyforms[ki].positions,
          storedRestForRebase,
          restGrid,
        )
        : (hasBinding && rigWarpKeyValues && typeof activeBinding.shiftFn === 'function')
          ? activeBinding.shiftFn(restGrid, gW, gH, rigWarpKeyValues[ki], gxSpan, gySpan, meshCtx)
          : new Float64Array(restGrid);

      rigWarpSpec.keyforms.push({
        keyTuple: rigWarpKeyValues ? rigWarpKeyValues[ki].slice() : [1],
        positions: new Float64Array(pos),
        opacity: 1,
      });

      const wdf = x.sub(rigKfsList, 'CWarpDeformerForm');
      const wdfAdf = x.sub(wdf, 'ACDeformerForm', { 'xs.n': 'super' });
      const wdfAcf = x.sub(wdfAdf, 'ACForm', { 'xs.n': 'super' });
      x.subRef(wdfAcf, 'CFormGuid', rigWarpFormGuids[ki], { 'xs.n': 'guid' });
      x.sub(wdfAcf, 'b', { 'xs.n': 'isAnimatedForm' }).text = 'false';
      x.sub(wdfAcf, 'b', { 'xs.n': 'isLocalAnimatedForm' }).text = 'false';
      x.subRef(wdfAcf, 'CWarpDeformerSource', pidRigWarpDf, { 'xs.n': '_source' });
      x.sub(wdfAcf, 'null', { 'xs.n': 'name' });
      x.sub(wdfAcf, 's', { 'xs.n': 'notes' }).text = '';
      x.sub(wdfAdf, 'f', { 'xs.n': 'opacity' }).text = '1.0';
      x.sub(wdfAdf, 'CFloatColor', {
        'xs.n': 'multiplyColor', red: '1.0', green: '1.0', blue: '1.0', alpha: '1.0',
      });
      x.sub(wdfAdf, 'CFloatColor', {
        'xs.n': 'screenColor', red: '0.0', green: '0.0', blue: '0.0', alpha: '1.0',
      });
      x.subRef(wdfAdf, 'CoordType', pidCoord, { 'xs.n': 'coordType' });
      x.sub(wdf, 'float-array', {
        'xs.n': 'positions', count: String(warpGridPts * 2),
      }).text = Array.from(pos).map(v => v.toFixed(6)).join(' ');
    }

    // Register in parent part's _childGuids
    const rigWarpPartSrc = groupParts.has(meshParentGroup) ? groupParts.get(meshParentGroup) : rootPart;
    rigWarpPartSrc.childGuidsNode.children.push(x.ref('CDeformerGuid', pidRigWarpGuid));
    rigWarpPartSrc.childGuidsNode.attrs.count = String(rigWarpPartSrc.childGuidsNode.children.length);

    // Store for re-parenting in section 3d. Face-parallax tags route to the single
    // FaceParallax warp; other tags route to Body X.
    rigWarpTargetNodesToReparent.push({
      node: rigWarpTargetNode, isFaceTag, isNeckTag,
      rigWarpSpecRef: rigWarpSpec, // for spec parent fix-up after reparent
    });

    // Tentative parent ahead of re-parenting; the re-parent block updates
    // both the XML ref AND this spec's parent so moc3 sees the FINAL parent.
    if (isFaceTag) rigWarpSpec.parent = { type: 'warp', id: 'FaceParallaxWarp' };
    else if (isNeckTag) rigWarpSpec.parent = { type: 'warp', id: 'NeckWarp' };
    else rigWarpSpec.parent = { type: 'warp', id: 'BodyXWarp' };

    rigCollector.warpDeformers.push(rigWarpSpec);
  }

  // BUG-018 — summary line so the user can see at a glance whether the
  // expected emit count matches reality. `skipped_noTag` is the most likely
  // culprit for missing RigWarp_front_hair (mesh.tag not 'front hair').
  logger.info('perPartRigWarps', `done: ${emitted} emitted, ${skipped_noTag} skip(noTag), ${skipped_alreadyEmitted} skip(alreadyEmitted), ${skipped_rigidFollow} skip(rigidFollow)`, {
    emitted, skipped_noTag, skipped_alreadyEmitted, skipped_rigidFollow,
    totalMeshes: perMesh.length,
  });
}
